biomage-org/api

.flux.yaml, .github/pull_request_template.md, .github/workflows/ci.yaml, .github/workflows/pr_validate.yaml, README.md, src/config/default-config.js, src/config/test-config.js, src/specs/api.v2.yaml, tests/config/__snapshots__/default-config-production.test.js.snap, tests/config/__snapshots__/default-config-staging-sandboxid.test.js.snap, tests/config/__snapshots__/default-config-staging.test.js.snap
Replace `hms-dbmi-cellenics` to `biomage-org`
N/A
N/A
N/A
master
=> Replace `hms-dbmi-cellenics` to `biomage-org`

src/api.v2/model/Experiment.js
=> Add newline

src/api.v2/controllers/experimentController.js, src/api.v2/model/Experiment.js, src/config/default-config.js, src/specs/api.v2.yaml, src/specs/models/experiment-bodies/ExperimentInfo.v2.yaml, src/specs/models/experiment-bodies/ExperimentsList.v2.yaml, src/sql/migrations/20220809193702_add_disabled_qc_rerun_attribute.js, tests/api.v2/controllers/experimentController.test.js, tests/api.v2/model/Experiment.test.js, tests/api.v2/model/__snapshots__/Experiment.test.js.snap
The QC pipeline is getting an upgrade. To make use of the upgrade, users have to rerun their experiments, causing. This PR adds :
- A migration to add the proper QC flag
- Modify schema to allow the processing of the qc flag in the API
- Process the QC flag corectly in the API
https://biomage.atlassian.net/browse/BIOMAGE-2061
N/A
UI - https://github.com/biomage-org/ui/pull/22
API - https://github.com/biomage-org/api/pull/10
master
**will not …
=> [BIOMAGE-2061] - Add QC Version & banner about complete pipeline rerun

src/api.v2/helpers/pipeline/handleQCResponse.js, src/api.v2/helpers/pipeline/hooks/updatePipelineVersion.js, src/specs/models/PipelineResponse.v2.yaml, tests/api.v2/helpers/pipeline/handleQCResponse.test.js, tests/api.v2/helpers/pipeline/hooks/__snapshots__/updatePipelineVersion.test.js.snap, tests/api.v2/helpers/pipeline/hooks/assignPodToPipeline.test.js, tests/api.v2/helpers/pipeline/hooks/sendNotification.test.js, tests/api.v2/helpers/pipeline/hooks/updatePipelineVersion.test.js
https://biomage.atlassian.net/browse/BIOMAGE-2076
https://ui-martinfosco-ui25-api12-pi.scp-staging.biomage.net/
N/A
https://github.com/biomage-org/ui/pull/25
https://github.com/biomage-org/pipeline/pull/20
master
=> 2076 Add pipelineVersion updates

src/api.v2/helpers/pipeline/gem2s.js, src/api.v2/model/Experiment.js, tests/api.v2/helpers/pipeline/__snapshots__/gem2s.test.js.snap, tests/api.v2/helpers/pipeline/gem2s.test.js
https://biomage.atlassian.net/browse/BIOMAGE-1987
N/A (in pipeline)
https://github.com/biomage-org/pipeline/pull/8
https://github.com/biomage-org/ui/pull/26
master
=> [BIOMAGE-2004] Merging in QC 

src/api.v2/middlewares/authMiddlewares.js, tests/api.v2/events/__snapshots__/handleWorkRequest.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/handleQCResponse.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineConstructors.test.js.snap, tests/api.v2/middlewares/authMiddlewares.test.js, tests/test-utils/constants.js
https://biomage.atlassian.net/browse/BIOMAGE-2090
https://ui-grasp6-api15.scp-staging.biomage.net/
master
=> [BIOMAGE-2090] Auth shows up as expired

src/api.v2/helpers/pipeline/pipelineConstruct/index.js, tests/api.v2/helpers/pipeline/__snapshots__/pipelineConstruct.test.js.snap, tests/api.v2/helpers/pipeline/pipelineConstruct.test.js
https://biomage.atlassian.net/browse/BIOMAGE-2133
https://ui-stefan-rm-steppc.scp-staging.biomage.net/
master
=> [BIOMAGE-2133] Pipeline steps disabled w/o user input

src/sql/migrations/20221013113149_add_sample_options.js
- Update migrations to skip empty experiments
- Update migraions to use correct column names
N/A
N/A
N/A
master
=> [BIOMAGE-2148] - Update migrations to skip empty experiments

src/specs/api.v2.yaml, tests/api.v2/routes/gem2s.test.js, tests/api.v2/routes/qc.test.js
When I was debugging the setup with a lambda function being triggered by the SNS work-results topic and the lambda function calling the api gem2sResults and pipelineResults api endpoints, I noticed that although media type `application/json` is accepted, in practice it doesn't work. The fact that it doesn't work is subtle to debug, because the error only indicates invalid json. In practice, we are not getting json, but a json string.
I am opening this PR to test if this is also the case with the architecture without the lambda, and if it is, we should remove this media type.
https://biomage.atlassian.net/browse/BIOMAGE-2142
N/A
master …
=> [BIOMAGE-2142] Remove media type that is not used

src/config/snsTopics.js
https://biomage.atlassian.net/browse/BIOMAGE-2174
https://ui-martinfosco-api34.scp-staging.biomage.net/
N/A
master
=> [2174] Fix post-registration-user-access

src/api.v2/helpers/cognito/__mocks__/getAwsPoolId.js, src/api.v2/helpers/cognito/__mocks__/getAwsProgrammaticClientInfo.js, src/api.v2/helpers/cognito/__mocks__/getUser.js, src/api.v2/helpers/cognito/getAwsPoolId.js, src/api.v2/helpers/cognito/getAwsProgrammaticClientInfo.js, src/api.v2/helpers/cognito/getUser.js, src/api.v2/middlewares/authMiddlewares.js, src/api.v2/routes/programmaticInterface.js, src/config/default-config.js, src/specs/api.v2.yaml, src/utils/aws/user.js, tests/api.v2/helpers/access/getExperimentUsers.test.js, tests/api.v2/helpers/cognito/__snapshots__/getAwsProgrammaticClientInfo.test.js.snap, tests/api.v2/helpers/cognito/__snapshots__/getUser.test.js.snap, tests/api.v2/helpers/cognito/getAwsProgrammaticClientInfo.test.js, tests/api.v2/helpers/cognito/getUser.test.js, tests/api.v2/routes/health.test.js, tests/api.v2/routes/kubernetes.test.js, tests/api.v2/routes/programmaticInterface.test.js
This PR just introduces a new endpoint `/programmaticInterfaceClient` to retrieve the cognito pool ID and region to be used by the programmatic interface.
**NOTE**  I recommend reviewing the work checking the commits as it is structured in 2 commits:
1. First one contains the refactor. 
2. Contains the new endpoint and associated functions.
Verify that the new endpoint works with:
`curl https://api-ahriman-api37.scp-staging.biomage.net/v2/programmaticInterfaceClient`
https://biomage.atlassian.net/browse/BIOMAGE-2215
https://ui-ahriman-api37.scp-staging.biomage.net
master
**You must check the box below** to run integration tests on the …
=> [BIOMAGE-2215] Programmatic client endpoint

.flux.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2223
https://ui-martinfosco-api42.scp-staging.biomage.net/
https://github.com/biomage-org/iac/pull/72
master
=> [2223] Fix duplicate ingress

.flux.yaml
=> Fix ingress?

src/api.v2/helpers/cognito/__mocks__/getUser.js, src/utils/aws/user.js
https://biomage.atlassian.net/browse/BIOMAGE-2243
N/A
master
=> [BIOMAGE-2243] Fix experiment sharing

.github/workflows/ci.yaml
Fix master manifest in `staging-candidates`
N/A
N/A
N/A
master
=> fix master manifest

src/specs/models/work-request-bodies/WorkRequestClusterCells.v2.yaml
Increase clustering resolution
https://biomage.atlassian.net/browse/BIOMAGE-2272
N/A
API - https://github.com/biomage-org/api/pull/60
UI - https://github.com/biomage-org/ui/pull/116
master
=> [BIOMAGE-2272] - Increase clustering resolution limit

.flux.yaml, .github/workflows/ci.yaml
Scope manifest path
https://biomage.atlassian.net/browse/BIOMAGE-2211
N/A
N/A
master
=> Scope manifest path

.github/pull_request_template.md
https://biomage.atlassian.net/browse/BIOMAGE-2275
N/A
master
=> pull request body template update

src/api.v2/helpers/pipeline/pipelineConstruct/constructors/createNewStep.js, src/api.v2/helpers/pipeline/pipelineConstruct/constructors/requestAssignPodToPipeline.js, src/config/default-config.js, src/config/test-config.js, tests/api.v2/helpers/pipeline/__snapshots__/pipelineConstruct.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineConstructors.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineSkeletons.test.js.snap, tests/config/__snapshots__/default-config-production.test.js.snap, tests/config/__snapshots__/default-config-staging-sandboxid.test.js.snap, tests/config/__snapshots__/default-config-staging.test.js.snap
https://biomage.atlassian.net/browse/BIOMAGE-2241
https://ui-martinfosco-api76.scp-staging.biomage.net/
N/A
master
=> [2241] Send apiUrl in each step

src/api.v2/helpers/pipeline/pipelineConstruct/constructors/createNewStep.js, src/api.v2/helpers/pipeline/pipelineConstruct/constructors/requestAssignPodToPipeline.js, tests/api.v2/helpers/pipeline/__snapshots__/pipelineConstruct.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineConstructors.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineSkeletons.test.js.snap
https://biomage.atlassian.net/browse/BIOMAGE-2241
https://ui-martinfosco-api77.scp-staging.biomage.net/
master
=> [2241] Move api url away from input

src/api.v2/model/UserAccess.js, src/config/default-config.js, src/config/test-config.js, src/utils/__mocks__/getAdminSub.js, src/utils/getAdminSub.js, tests/api.v2/model/UserAccess.test.js, tests/config/__snapshots__/default-config-production.test.js.snap, tests/config/__snapshots__/default-config-staging-sandboxid.test.js.snap, tests/config/__snapshots__/default-config-staging.test.js.snap, tests/utils/__snapshots__/getAdminSub.test.js.snap, tests/utils/getAdminSub.test.js
Add correct admin account to newly created experiments, according to user pool id of the deployment.
Staging: https://ui-agi-api81.scp-staging.biomage.net/
https://biomage.atlassian.net/browse/BIOMAGE-2197
N/A
N/A
master
=> [BIOMAGE-2197] - Add correct admin account

src/api.v2/helpers/pipeline/gem2s.js, tests/api.v2/controllers/sampleFileController.test.js, tests/api.v2/helpers/pipeline/__snapshots__/gem2s.test.js.snap, tests/api.v2/helpers/pipeline/gem2s.test.js, tests/api.v2/helpers/pipeline/pipelineConstruct.test.js, tests/api.v2/mocks/data/gem2sUploadToAWSPayload.json
https://biomage.atlassian.net/browse/BIOMAGE-2285
https://ui-martinfosco-api79-pipeline.scp-staging.biomage.net/
N/A
https://github.com/biomage-org/pipeline/pull/100
master
=> [2285] Big sns messages v1

src/api.v2/helpers/pipeline/pipelineConstruct/constructors/submitBatchJob.js, src/config/default-config.js, src/config/test-config.js, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineSkeletons.test.js.snap, tests/config/__snapshots__/default-config-production.test.js.snap, tests/config/__snapshots__/default-config-staging-sandboxid.test.js.snap, tests/config/__snapshots__/default-config-staging.test.js.snap
Pass Datadog API and APP keys to Batch
https://biomage.atlassian.net/browse/BIOMAGE-2264
N/A
IAC - https://github.com/biomage-org/iac/pull/92
API - https://github.com/biomage-org/api/pull/80
Pipeline - https://github.com/biomage-org/pipeline/pull/99
master
=> [BIOMAGE-2264] - Pass datadog keys to batch

src/api.v2/helpers/pipeline/hooks/sendNotification.js
Revert forgotten revert in PR #85
N/A
N/A
N/A
master
=> Revert forgotten revert in PR #85

src/sql/migrations/20230111112324_unique-sample-names.js
https://biomage.atlassian.net/browse/BIOMAGE-2327
https://ui-stefan-api90.scp-staging.biomage.net/data-management
master
=> [BIOMAGE-2327] Enforce unique sample names in data management

src/api.v2/helpers/pipeline/hooks/sendNotification.js
Revert changes that were written for testing
N/A
N/A
master
=> Revert test changes

src/api.v2/controllers/__mocks__/metadataTrackController.js, src/api.v2/controllers/metadataTrackController.js, src/api.v2/model/MetadataTrack.js, src/api.v2/model/__mocks__/MetadataTrack.js, src/api.v2/routes/metadataTrack.js, src/specs/api.v2.yaml, tests/api.v2/controllers/metadataTrackController.test.js, tests/api.v2/model/MetadataTrack.test.js, tests/api.v2/model/__snapshots__/MetadataTrack.test.js.snap, tests/api.v2/routes/metadataTrack.test.js
New endpoint accepting a string to "bulk" update metadata.
Can be tested with (substitute sample names accordingly)
```
curl -XPATCH https://api-ahriman-api95.scp-staging.biomage.net/v2/experiments/${EXPERIMENT_ID}/metadataTracks -H 'Content-Type: text/plain' -d $'Acute\tmetadata_key_4\tmetadata_value_1\nConvalescent\tmetadata_key_4\tmetadata_value_3' -H "Authorization: Bearer ${TOKEN}"
```
Integration tests run in the other UI PR.
https://biomage.atlassian.net/browse/BIOMAGE-2354
N/A
https://github.com/biomage-org/api/pull/95
https://github.com/biomage-org/ui/pull/161
master
Integration tests have to …
=> [BIOMAGE-2354] Bulk update metadata

src/api.v2/controllers/experimentController.js, src/api.v2/model/Experiment.js, src/api.v2/model/Sample.js, src/specs/api.v2.yaml, tests/api.v2/controllers/experimentController.test.js, tests/api.v2/model/Sample.test.js, tests/api.v2/model/__snapshots__/Sample.test.js.snap
https://biomage.atlassian.net/browse/BIOMAGE-2310
N/A (https://ui-martinfosco-ui158-api99.scp-staging.biomage.net/)
https://github.com/biomage-org/ui/pull/158
master
=> [2310] Fix issue when closing ui while files ar ebeing created

src/specs/models/WorkRequestBodies.v2.yaml, src/specs/models/work-request-bodies/WorkRequestScTypeAnnotate.v2.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2358
https://ui-martinfosco-ui168-api109.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/168
master
=> [2358] Add work request body of ScTypeAnnotate

src/api.v2/model/Experiment.js, src/specs/api.v2.yaml, src/specs/models/experiment-bodies/ExampleExperimentsList.v2.yaml, src/sql/migrations/20230207141717_add_example_experiment_fields.js, tests/api.v2/mocks/getMockSqlClient.js, tests/api.v2/model/Experiment.test.js
Adds new fields for all experiments used in the experiment repository table.
New fields added are:
- publicationTitle
- publicationUrl
- dataSourceTitle
- dataSourceUrl
- species
- cellCount
The reason for separating the titles from urls is so the text displayed can be different from the actual url:
e.g: [10x Genomics website](https://www.10xgenomics.com/resources/datasets) as opposed to the raw url.
https://biomage.atlassian.net/browse/BIOMAGE-2387
N/A
UI - https://github.com/biomage-org/ui/pull/170
API - https://github.com/biomage-org/api/pull/111
Tests - https://github.com/biomage-org/testing/pull/9
master
**You must check the box below** to run integration tests on the latest commit on your PR …
=> [BIOMAGE-2386] Example experiment fields

tests/test-utils/mockAWSServices.js
=> remove unused mocks of S3 delete

.secrets.baseline, src/api.v2/events/validateAndSubmitWork.js, src/api.v2/helpers/pipeline/__mocks__/getPipelineStatus.js, src/api.v2/helpers/pipeline/handleQCResponse.js, src/api.v2/helpers/worker/__mocks__/createObjectHash.js, src/api.v2/helpers/worker/__mocks__/getWorkerStatus.js, src/api.v2/helpers/worker/createObjectHash.js, src/api.v2/helpers/worker/workSubmit/getExtraDependencies.js, src/api.v2/helpers/worker/workSubmit/submitEmbeddingWork.js, src/api.v2/helpers/worker/workSubmit/submitMarkerHeatmapWork.js, src/api.v2/helpers/worker/workSubmit/submitWork.js, src/api.v2/helpers/worker/workerVersions.js, src/api.v2/model/Experiment.js, src/config/default-config.js, src/config/test-config.js, tests/api.v2/helpers/worker/__snapshots__/submitEmbeddingWork.test.js.snap, tests/api.v2/helpers/worker/__snapshots__/submitMarkerHeatmapWork.test.js.snap, tests/api.v2/helpers/worker/submitEmbeddingWork.test.js, tests/api.v2/helpers/worker/submitMarkerHeatmapWork.test.js, tests/api.v2/mocks/data/getProcessingConfigResponse.json, tests/config/__snapshots__/default-config-production.test.js.snap, tests/config/__snapshots__/default-config-staging-sandboxid.test.js.snap, tests/config/__snapshots__/default-config-staging.test.js.snap
This PR triggers the default embedding & marker heatmap in a hook after the configure embedding step of the pipeline so data exploration will load faster the first time user lands there.
https://biomage.atlassian.net/browse/BIOMAGE-2301
N/A
https://github.com/biomage-org/ui/pull/183
https://github.com/biomage-org/api/pull/110
master
=> [BIOMAGE-2301] Triggering embedding & marker heatmap after qc run

src/api.v2/helpers/pipeline/getPipelineStatus.js, src/api.v2/helpers/pipeline/pipelineConstruct/constructors/qcStepNameTranslations.js, src/api.v2/helpers/pipeline/pipelineConstruct/index.js, src/api.v2/helpers/pipeline/pipelineConstruct/qcHelpers.js, src/api.v2/helpers/s3/fileExists.js, tests/api.v2/helpers/pipeline/getPipelineStatus.test.js, tests/api.v2/helpers/pipeline/pipelineConstruct/__snapshots__/qcHelpers.test.js.snap, tests/api.v2/helpers/pipeline/pipelineConstruct/qcHelpers.test.js
https://biomage.atlassian.net/browse/BIOMAGE-2302
https://ui-martinfosco-ui179-api113.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/179
master
=> [2302] Resume qc from error

src/specs/models/work-request-bodies/WorkRequestTrajectoryAnalysisGetPseudoTime.v2.yaml, src/specs/models/work-request-bodies/WorkRequestTrajectoryAnalysisGetStartingNodes.v2.yaml, src/utils/plotConfigInvalidation/invalidatePlotsForEvent.js, tests/api.v2/mocks/data/invalidationResults.js, tests/utils/plotConfigInvalidation/__snapshots__/invalidatePlotsForEvent.test.js.snap
Change work request shape to accommodate custom cell sets
https://biomage.atlassian.net/browse/BIOMAGE-2111
N/A
UI - https://github.com/biomage-org/ui/pull/182
API - https://github.com/biomage-org/api/pull/114
Worker - https://github.com/biomage-org/worker/pull/69
master
=> [BIOMAGE-2111] - Use selected cell sets in Trajectory Plot

src/api.v2/helpers/pipeline/pipelineConstruct/constructors/submitBatchJob.js, tests/api.v2/helpers/pipeline/__snapshots__/stateMachineSkeletons.test.js.snap
Suffix the pipeline Batch job definition with the sandbox id
https://biomage.atlassian.net/browse/BIOMAGE-2328
N/A
N/A
master
=> [BIOMAGE-2328] - Add sandbox id to batch jobdef

src/api.v2/controllers/experimentController.js
https://biomage.atlassian.net/browse/BIOMAGE-2265
N/A
master
=> changed default memory values for staging

src/api.v2/helpers/pipeline/pipelineConstruct/index.js, tests/api.v2/helpers/pipeline/__snapshots__/pipelineConstruct.test.js.snap
https://biomage.atlassian.net/browse/BIOMAGE-2420
https://ui-martinfosco-api128-pipelin.scp-staging.biomage.net/
https://github.com/biomage-org/pipeline/pull/142
master
=> [BIOMAGE-2420] Added workaround parameter to recompute doublet scores

src/api.v2/helpers/worker/workSubmit/getExtraDependencies.js, src/specs/models/WorkRequestBodies.v2.yaml, src/specs/models/work-request-bodies/WorkRequestDownloadAnnotSeuratObject.v2.yaml
https://biomage.atlassian.net/browse/BIOMAGE-2439
N/A https://ui-martinfosco-ui208-api129.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/208
master
=> [2439] Download processed rds with annotations

src/api.v2/helpers/pipeline/handleQCResponse.js, src/api.v2/helpers/pipeline/pipelineConstruct/index.js, src/api.v2/model/Experiment.js, tests/api.v2/helpers/pipeline/__snapshots__/handleQCResponse.test.js.snap, tests/api.v2/helpers/pipeline/__snapshots__/pipelineConstruct.test.js.snap, tests/api.v2/helpers/pipeline/handleQCResponse.test.js, tests/api.v2/helpers/pipeline/pipelineConstruct.test.js
https://biomage.atlassian.net/browse/BIOMAGE-2440
N/A https://ui-martinfosco-ui214-api132-p.scp-staging.biomage.net/
https://github.com/biomage-org/pipeline/pull/149
https://github.com/biomage-org/ui/pull/214
master
=> [2440] Improve processing config values persistence

.github/workflows/ci.yaml, .github/workflows/pr_validate.yaml
Update set output to new syntax
https://biomage.atlassian.net/browse/BIOMAGE-2347
N/A
IAC - https://github.com/biomage-org/iac/pull/155
UI - https://github.com/biomage-org/ui/pull/213
API - https://github.com/biomage-org/api/pull/136
Pipeline - https://github.com/biomage-org/pipeline/pull/151
Worker - https://github.com/biomage-org/worker/pull/88
master
=> [BIOMAGE-2347] - Update set output syntax

src/api.v2/helpers/roles.js
https://biomage.atlassian.net/browse/BIOMAGE-2390
N/A
master
=> [2390] Fix regex for plots endpoints

.github/workflows/ci.yaml, src/sql/migrations/20230112174046_add_parent_experiment_id_table.js
=> temporarily disable admin enforcement

src/api.v2/helpers/access/createUserInvite.js, src/api.v2/model/Experiment.js
N/A
N/A https://ui-martinfosco-ui230-api150.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/230
master
=> Add share error handling

Makefile
Improve make install command
N/A
N/A
N/A
master
=> Change install command

src/api.v2/controllers/experimentController.js, src/api.v2/model/ExperimentExecution.js, src/api.v2/model/ExperimentParent.js, src/api.v2/model/__mocks__/ExperimentParent.js, tests/api.v2/controllers/experimentController.test.js, tests/api.v2/model/ExperimentParent.test.js
N/A
N/A
https://ui-martinfosco-ui241-api159.scp-staging.biomage.net/
https://github.com/biomage-org/ui/pull/241
master
=> Support cloning subset experiments

src/api.v2/helpers/s3/signedUrl.js, src/specs/models/samples-bodies/CreateSamples.v2.yaml, src/sql/migrations/20230621132513_add_10xh5_technology.js
Add support for h5 technology. 
https://github.com/biomage-org/issues/issues/134
N/A
[UI#240](https://github.com/biomage-org/ui/pull/240)
master
=> Upload h5 to s3

tests/api.v2/model/ExperimentExecution.test.js, tests/api.v2/model/__snapshots__/ExperimentExecution.test.js.snap
=> Fix test from hms merge

.github/pull_request_template.md, README.md
=> Pre-merge pending changes

src/api.v2/middlewares/authMiddlewares.js
=> Disable privacy check in the local environment

.github/workflows/pr_validate.yaml
=> Remove check-issue-url
